# Generated by Django 4.2.1 on 2024-11-05 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('username', models.CharField(default='', max_length=30, unique=True, verbose_name='Имя пользователя')),
                ('password', models.TextField(max_length=256, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь суперюзером?')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'CustomUser',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(db_column='action_id', primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=50, verbose_name='Название действия')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
                'db_table': 'Action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.AutoField(db_column='collection_id', primary_key=True, serialize=False)),
                ('collection_name', models.CharField(max_length=150, verbose_name='Название коллекции')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото коллекции')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания коллекции')),
                ('time_create', models.TimeField(auto_now_add=True, verbose_name='Время создания коллекции')),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Сформирован'), (2, 'Удалён')], default=0)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'db_table': 'Collection',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.AutoField(db_column='plant_id', primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=150, verbose_name='Название растения')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото растения')),
                ('general_info', models.CharField(max_length=255, verbose_name='Описание растения')),
                ('properties', models.JSONField(verbose_name='Характеристики растения')),
                ('status', models.CharField(choices=[('a', 'active'), ('d', 'delited')], default='a', max_length=1, verbose_name='Статус растения')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
                'db_table': 'Plant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plant_Class',
            fields=[
                ('plant_class_id', models.AutoField(db_column='plant_class_id', primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100, verbose_name='Название класса растения')),
            ],
            options={
                'verbose_name': 'Класс растения',
                'verbose_name_plural': 'Классы растений',
                'db_table': 'Plant_Class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plant_Subclass',
            fields=[
                ('plant_subclass_id', models.AutoField(db_column='plant_subclass_id', primary_key=True, serialize=False)),
                ('subclass_name', models.CharField(max_length=100, verbose_name='Название подкласса растения')),
                ('plant_class', models.ForeignKey(db_column='plant_class_id', on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='backend_plants.plant_class', verbose_name='Название класса растения')),
            ],
            options={
                'verbose_name': 'Подкласс растения',
                'verbose_name_plural': 'Подклассы растений',
                'db_table': 'Plant_Subclass',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('recommendation_id', models.AutoField(db_column='recommendation_id', primary_key=True, serialize=False)),
                ('last_modified_date', models.DateField(auto_now=True, verbose_name='Дата последнего изменения рекомендации')),
                ('last_modified_time', models.TimeField(auto_now=True, verbose_name='Время последнего изменения рекомендации')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'db_table': 'Recommendation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('admin_id', models.AutoField(db_column='admin_id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
                'db_table': 'AdminUser',
                'managed': True,
            },
            bases=('backend_plants.customuser',),
        ),
        migrations.CreateModel(
            name='RecommendationPlant',
            fields=[
                ('recommendation_plant_id', models.AutoField(db_column='recommendation_plant_id', primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=5, verbose_name='Вес растения в рекомендации')),
                ('plant', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.plant', verbose_name='Растение')),
                ('recommendation', models.ForeignKey(db_column='recommendation_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.recommendation', verbose_name='Рекомендация')),
            ],
            options={
                'verbose_name': 'РекомендацияРастение',
                'db_table': 'RecommendationPlant',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='includes_plants',
            field=models.ManyToManyField(through='backend_plants.RecommendationPlant', to='backend_plants.plant'),
        ),
        migrations.CreateModel(
            name='Plant_Type',
            fields=[
                ('plant_type_id', models.AutoField(db_column='plant_type_id', primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, verbose_name='Название подкласса растения')),
                ('plant_subclass', models.ForeignKey(db_column='plant_subclass_id', on_delete=django.db.models.deletion.CASCADE, related_name='types', to='backend_plants.plant_subclass', verbose_name='Название подкласса растения')),
            ],
            options={
                'verbose_name': 'Вид растения',
                'verbose_name_plural': 'Виды растений',
                'db_table': 'Plant_Type',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_class',
            field=models.ForeignKey(db_column='plant_class_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.plant_class', verbose_name='Название класса растения'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_subclass',
            field=models.ForeignKey(blank=True, db_column='plant_subclass_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend_plants.plant_subclass', verbose_name='Название подкласса растения'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(db_column='plant_type_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.plant_type', verbose_name='Название вида растения'),
        ),
        migrations.CreateModel(
            name='CollectionPlant',
            fields=[
                ('collection_plant_id', models.AutoField(db_column='collection_plant_id', primary_key=True, serialize=False)),
                ('date_add', models.DateField(auto_now=True, verbose_name='Дата обновления растений в коллекции')),
                ('time_add', models.TimeField(auto_now=True, verbose_name='Время обновления растений в коллекции')),
                ('collection', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.collection', verbose_name='Коллекция')),
                ('plant', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'КоллекцияРастение',
                'db_table': 'CollectionPlant',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='includes_plants',
            field=models.ManyToManyField(through='backend_plants.CollectionPlant', to='backend_plants.plant'),
        ),
        migrations.AddField(
            model_name='collection',
            name='recommendation',
            field=models.ForeignKey(blank=True, db_column='recommendation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_plants.recommendation'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('interaction_id', models.AutoField(db_column='interaction_id', primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата взаимодействия админа с растением')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время взаимодействия админа с растением')),
                ('action', models.ForeignKey(db_column='action_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.action')),
                ('plant', models.ForeignKey(db_column='plant_id', on_delete=django.db.models.deletion.CASCADE, to='backend_plants.plant', verbose_name='Растение')),
                ('admin', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_id', to='backend_plants.adminuser')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'db_table': 'Interaction',
                'managed': True,
            },
        ),
    ]
