# Generated by Django 4.2.1 on 2024-11-05 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_type',
            name='plant_subclass',
            field=models.ForeignKey(blank=True, db_column='plant_subclass_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='backend_plants.plant_subclass', verbose_name='Название подкласса растения'),
        ),
    ]
