# Generated by Django 4.2.1 on 2024-11-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0002_alter_plant_type_plant_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant_class',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото класса растения'),
        ),
        migrations.AddField(
            model_name='plant_subclass',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото подкласса растения'),
        ),
    ]
