# Generated by Django 4.2.1 on 2024-11-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0003_plant_class_image_url_plant_subclass_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='image_url',
            new_name='image_url_collection',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image_url',
            new_name='image_url_plant',
        ),
        migrations.RenameField(
            model_name='plant_class',
            old_name='image_url',
            new_name='image_url_class',
        ),
        migrations.RenameField(
            model_name='plant_subclass',
            old_name='image_url',
            new_name='image_url_subclass',
        ),
    ]
