# Generated by Django 4.2.1 on 2024-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0004_rename_image_url_collection_image_url_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='general_info',
            field=models.CharField(max_length=1500, verbose_name='Описание растения'),
        ),
    ]
