# Generated by Django 4.2.1 on 2024-12-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0005_alter_plant_general_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='recommendation',
        ),
    ]
