# Generated by Django 4.2.1 on 2025-01-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0007_recommendation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Recommendation',
            fields=[
                ('type_rec_id', models.AutoField(db_column='type_rec_id', primary_key=True, serialize=False)),
                ('type_rec_name', models.CharField(max_length=50, verbose_name='Название типа рекомендации')),
            ],
        ),
    ]
