# Generated by Django 4.2.1 on 2025-01-28 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0008_type_recommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type_recommendation',
            options={'managed': True, 'verbose_name': 'Тип рекомендации', 'verbose_name_plural': 'Типы рекомендации'},
        ),
        migrations.AlterModelTable(
            name='type_recommendation',
            table='Type_Recommendation',
        ),
    ]
