# Generated by Django 4.2.1 on 2025-01-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0009_alter_type_recommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='rec_type_id',
            field=models.ForeignKey(db_column='rec_type_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_plants.type_recommendation', verbose_name='Название типа рекомендации'),
        ),
    ]
