# Generated by Django 4.2.1 on 2025-01-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0010_recommendation_rec_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='collection',
            field=models.ForeignKey(db_column='for_col_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_plants.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='plant',
            field=models.ForeignKey(db_column='for_plant_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_plants.plant', verbose_name='Растение'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='includes_plants',
            field=models.ManyToManyField(related_name='recommended_in', through='backend_plants.RecommendationPlant', to='backend_plants.plant'),
        ),
    ]
