# Generated by Django 4.2.1 on 2025-01-28 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0011_recommendation_collection_recommendation_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(db_column='user_id', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
