# Generated by Django 4.2.1 on 2025-01-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0012_alter_recommendation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='rec_type_id',
            new_name='type_rec',
        ),
    ]
