# Generated by Django 4.2.1 on 2025-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0013_rename_rec_type_id_recommendation_type_rec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Сформирован'), (2, 'Удалён')], default=1),
        ),
    ]
