# Generated by Django 4.2.1 on 2025-02-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_plants', '0014_alter_collection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image_url_collection',
        ),
    ]
